ALTER TABLE CONSUMER ADD CONSTRAINT CHECK_GENDER CHECK (Gender = 'F' OR Gender = 'M');
ALTER TABLE CONSUMER ADD CONSTRAINT CHECK_PWD_LEN CHECK (LEN(Login_password) >= 6);
ALTER TABLE CONSUMER ADD CONSTRAINT CHECK_AGE CHECK (YEAR(Birth_date) <= YEAR(GETDATE()) - 18);
ALTER TABLE DEPT_PASSWORD ADD CONSTRAINT CHECK_PSW_DEPT CHECK (DEPT_ins_pwd != DEPT_stu_pwd);
ALTER TABLE COURSE_PASSWORD ADD CONSTRAINT CHECK_PSW_COURSE CHECK (Course_ins_pwd != Course_stu_pwd);
ALTER TABLE SUBMISSION ADD CONSTRAINT CHECK_GRADE CHECK (Grade BETWEEN 0 AND 100);
ALTER TABLE CONSUMER_MESSAGE ADD CONSTRAINT CHECK_MESSAGE_RECEIVER CHECK (Sender_consumer != Receiver_consumer);
ALTER TABLE CONSUMER_MESSAGE ADD CONSTRAINT CHECK_MESSAGE_TIME CHECK (Send_date < GETDATE());
ALTER TABLE CONSUMER_SKILL_ENDORSE ADD CONSTRAINT CHECK_WHO_ENDORSED CHECK (Endorsed_consumer != Endorsed_by);
ALTER TABLE POST ADD CONSTRAINT CHECK_POST_TIME CHECK (Post_time < GETDATE());
ALTER TABLE COMMENT ADD CONSTRAINT CHECK_SEND_TIME CHECK (Comment_time < GETDATE());
ALTER TABLE COURSE ADD CONSTRAINT CHECK_SEM CHECK (Course_sem = '1' OR Course_sem = '2');
ALTER TABLE ASSIGNMENT ADD CONSTRAINT CHECK_DATE_ASSIGN CHECK (Assn_start_date < Assn_end_date);
ALTER TABLE GETS_EDUCATION ADD CONSTRAINT CHECK_DATE_EDU CHECK (Edu_start_date < Edu_end_date);
ALTER TABLE WORKS_FOR ADD CONSTRAINT CHECK_DATE_WORK CHECK (	(Work_end_date IS NULL AND Work_start_date < GETDATE()) OR 
																(Work_end_date IS NOT NULL AND Work_start_date < Work_end_date AND Work_end_date < GETDATE())	
															);