DELETE FROM CONSUMER WHERE Fname = 'Kemal';
DELETE FROM CONSUMER_COURSE WHERE Course_name = 'Olasýlýk ve Ýstatistik';
DELETE FROM WORKS_FOR WHERE YEAR(Work_start_date) = 2018;
DELETE FROM SKILL WHERE Skill_name LIKE '_l%';
DELETE FROM POST WHERE YEAR(Post_time) = 2020;
DELETE FROM COMPANY WHERE City = 'Manisa';
